// Generated by CoffeeScript 1.10.0
(function() {
  var day, dayz, i, len, moused, reCalc, seldayz, selection, x1, x2, x3, x4, y1, y2, y3, y4;

  selection = document.getElementById('ant-select');

  x1 = 0;

  y1 = 0;

  x2 = 0;

  y2 = 0;

  x3 = 0;

  y3 = 0;

  x4 = 0;

  y4 = 0;

  moused = false;

  dayz = document.getElementsByClassName('calendar-year-month__day');

  for (i = 0, len = dayz.length; i < len; i++) {
    day = dayz[i];
    day.style.backgroundColor = "white";
  }

  seldayz = [];

  reCalc = function() {
    x3 = Math.min(x1, x2);
    x4 = Math.max(x1, x2);
    y3 = Math.min(y1, y2);
    y4 = Math.max(y1, y2);
    selection.style.left = x3 + 'px';
    selection.style.top = y3 + 'px';
    selection.style.width = x4 - x3 + 'px';
    return selection.style.height = y4 - y3 + 'px';
  };

  document.addEventListener("mousedown", function(e) {
    moused = true;
    selection.hidden = 0;
    x1 = e.clientX;
    y1 = e.clientY;
    return reCalc();
  });

  document.addEventListener("mousemove", function(e) {
    var j, k, len1, len2, results;
    x2 = e.clientX;
    y2 = e.clientY;
    reCalc();
    for (j = 0, len1 = dayz.length; j < len1; j++) {
      day = dayz[j];
      if (moused === true) {
        if (day.getBoundingClientRect().right > x3 && day.getBoundingClientRect().left < x4 && day.getBoundingClientRect().bottom > y3 && day.getBoundingClientRect().top < y4) {
          if (day.style.backgroundColor === "white") {
            day.style.backgroundColor = "#3399cc";
          }
        }
      }
    }
    results = [];
    for (k = 0, len2 = selddayz.length; k < len2; k++) {
      day = selddayz[k];
      if (day.style.backgroundColor === "white") {
        results.push(day.style.backgroundColor = "#3399cc");
      } else {
        results.push(day.style.backgroundColor = "#3399cc");
      }
    }
    return results;
  });

  document.addEventListener("mouseup", function(e) {
    var j, len1, results;
    selection.hidden = 1;
    moused = false;
    seldayz = [];
    results = [];
    for (j = 0, len1 = dayz.length; j < len1; j++) {
      day = dayz[j];
      if (day.style.backgroundColor === "#3399cc") {
        results.push(seldayz.push(day));
      } else {
        results.push(void 0);
      }
    }
    return results;
  });

}).call(this);
