// Generated by CoffeeScript 1.10.0
(function() {
  var day, dayz, j, len, moused, reCalc, seldayz, selection, x1, x2, x3, x4, y1, y2, y3, y4;

  selection = document.getElementById('ant-select');

  x1 = 0;

  y1 = 0;

  x2 = 0;

  y2 = 0;

  x3 = 0;

  y3 = 0;

  x4 = 0;

  y4 = 0;

  moused = false;

  dayz = document.getElementsByClassName('calendar-year-month__day');

  for (j = 0, len = dayz.length; j < len; j++) {
    day = dayz[j];
    day.style.backgroundColor = "white";
  }

  seldayz = dayz;

  reCalc = function() {
    x3 = Math.min(x1, x2);
    x4 = Math.max(x1, x2);
    y3 = Math.min(y1, y2);
    y4 = Math.max(y1, y2);
    selection.style.left = x3 + 'px';
    selection.style.top = y3 + 'px';
    selection.style.width = x4 - x3 + 'px';
    return selection.style.height = y4 - y3 + 'px';
  };

  document.addEventListener("mousedown", function(e) {
    moused = true;
    selection.hidden = 0;
    x1 = e.clientX;
    y1 = e.clientY;
    return reCalc();
  });

  document.addEventListener("mousemove", function(e) {
    var i, k, ref, results, selday;
    x2 = e.clientX;
    y2 = e.clientY;
    reCalc();
    results = [];
    for (i = k = 0, ref = dayz.length; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
      day = dayz[i];
      selday = seldayz[i];
      if (moused) {
        if (day.getBoundingClientRect().right > x3 && day.getBoundingClientRect().left < x4 && day.getBoundingClientRect().bottom > y3 && day.getBoundingClientRect().top < y4) {
          if (selday.style.backgroundColor = "white") {
            results.push(day.style.backgroundColor = "#3399cc");
          } else {
            results.push(day.style.backgroundColor = "white");
          }
        } else {
          results.push(void 0);
        }
      } else {
        results.push(void 0);
      }
    }
    return results;
  });

  document.addEventListener("mouseup", function(e) {
    selection.hidden = 1;
    moused = false;
    return seldayz = dayz;
  });

}).call(this);
