// Generated by CoffeeScript 1.10.0
(function() {
  var day, dayz, j, k, len, moused, reCalc, seldayz, selection, x1, x2, x3, x4, y1, y2, y3, y4;

  selection = document.getElementById('ant-select');

  x1 = 0;

  y1 = 0;

  x2 = 0;

  y2 = 0;

  x3 = 0;

  y3 = 0;

  x4 = 0;

  y4 = 0;

  moused = false;

  seldayz = [];

  dayz = [];

  dayz = document.getElementsByClassName('calendar-year-month__day');

  k = -1;

  for (j = 0, len = dayz.length; j < len; j++) {
    day = dayz[j];
    k = k + 1;
    day.style.backgroundColor = "white";
    if (day.style.backgroundColor === "white") {
      seldayz[k] = 1;
    } else {
      seldayz[k] = 0;
    }
    console.log(seldayz[k]);
  }

  reCalc = function() {
    x3 = Math.min(x1, x2);
    x4 = Math.max(x1, x2);
    y3 = Math.min(y1, y2);
    y4 = Math.max(y1, y2);
    selection.style.left = x3 + 'px';
    selection.style.top = y3 + 'px';
    selection.style.width = x4 - x3 + 'px';
    return selection.style.height = y4 - y3 + 'px';
  };

  document.addEventListener("mousedown", function(e) {
    moused = true;
    selection.hidden = 0;
    x1 = e.clientX;
    y1 = e.clientY;
    return reCalc();
  });

  document.addEventListener("mousemove", function(e) {
    var i, l, len1, results;
    x2 = e.clientX;
    y2 = e.clientY;
    reCalc();
    if (moused) {
      i = -1;
      results = [];
      for (l = 0, len1 = dayz.length; l < len1; l++) {
        day = dayz[l];
        i = i + 1;
        if (day.getBoundingClientRect().right > x3 && day.getBoundingClientRect().left < x4 && day.getBoundingClientRect().bottom > y3 && day.getBoundingClientRect().top < y4) {
          if (seldayz[i] === 0) {
            results.push(day.style.backgroundColor = "white");
          } else {
            results.push(day.style.backgroundColor = "#3399cc");
          }
        } else {
          if (seldayz[i] === 1) {
            results.push(day.style.backgroundColor = "white");
          } else {
            results.push(day.style.backgroundColor = "#3399cc");
          }
        }
      }
      return results;
    }
  });

  document.addEventListener("mouseup", function(e) {
    var l, len1, results;
    selection.hidden = 1;
    moused = false;
    k = -1;
    results = [];
    for (l = 0, len1 = dayz.length; l < len1; l++) {
      day = dayz[l];
      k = k + 1;
      if (day.style.backgroundColor === "white") {
        seldayz[k] = 1;
      } else {
        seldayz[k] = 0;
      }
      results.push(console.log(seldayz[k]));
    }
    return results;
  });

}).call(this);
